name = "nifty50-api-mohit-dev"
main = "src/index.js"
compatibility_date = "2022-10-19"

kv_namespaces = [
  { binding = "NIFTY50", id = "4b76c641775943a5b3d8ed8c93c24770", preview_id = "b6eea12c8243475d8297e3b89ba6eb88" }
]

[triggers]
crons = ["0 4,5,6,7,8,9,10,11 * * *"]
